service: phish-viz

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  apiKeys:
    - phish-viz-${opt:stage, 'dev'}
  environment:
    STAGE: ${opt:stage, 'dev'}

package:
  exclude:
    - node_modules/**

functions:
  helloworld:
    handler: libwrapper.hello_world
    events:
      - http:
        path: model
        method: get
        private: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: ../venv/bin/python
    pipCmdExtraArgs:
      - -f
      - ./../dist