service: phish-viz

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  apiKeys:
    - phish-viz-${opt:stage, 'dev'}
  environment:
    STAGE: ${opt:stage, 'dev'}
    PHISH_NET_BASE_URL: https://api.phish.net/v3/
    PHISH_NET_API_KEY: ${env:PHISH_NET_API_KEY}

package:
  exclude:
    - node_modules/**

functions:
  test:
    handler: libwrapper.test_wrapper
    events:
      - http:
          path: test
          method: get
          private: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: ../venv/bin/python
    pipCmdExtraArgs:
      - -f
      - ./../dist